### ISSUE TITLE
jirafs.commands.preview doesn't work on Python 3.6

### ISSUE THREAD

**Issue by commonquail** [coddingtonbear/jirafs#65]
```
(venv) $ python3
Python 3.6.12 (default, Dec 02 2020, 09:44:23) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jirafs.commands.preview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../jira/venv/lib64/python3.6/site-packages/jirafs/commands/preview/__init__.py", line 11, in <module>
    from http.server import ThreadingHTTPServer
ImportError: cannot import name 'ThreadingHTTPServer'
```

Comparing

- https://docs.python.org/3.6/library/http.server.html
- https://docs.python.org/3.7/library/http.server.html

it looks like `ThreadingHTTPServer` was added in 3.7.
